---
title: "CAPE/SHEAR vs Cluster Characteristics"
author: "James Elsner"
output: html_document
editor_options: 
  chunk_output_type: console
---

Load packages.
```{r}
library(dplyr)
library(sf)
library(ggplot2)
library(lme4)
library(lubridate)
library(xtable)
```

Load the cluster-level tornado data.
```{r}
load("BigDays.RData")

BigDays.sfdfT <- BigDays.sfdfT %>%
  mutate(A = as.numeric(HullArea)/10^10,
         CAPE = maxCAPE/1000,
         CIN = minCIN/100,
         DLBS = maxBS_deep/10,
         SLBS = maxBS_shallow/10,
         P = totalPOP/100000)
dim(BigDays.sfdfT)
```

## Distribution of casualties
```{r}
BigDays.sfdfT %>%
  st_drop_geometry() %>%
  group_by(GroupDayCas) %>%
  summarize(nC = n(),
            pC = nC/nrow(BigDays.sfdfT)) %>%
  arrange(desc(nC))
```

## Tornado count model

Consider only CAPE, CIN, BS (deep & shallow)
```{r}
library(MASS)

modelInitial <- glm.nb(nT ~ A + Lat + Lon + Year + CAPE + CIN + DLBS + SLBS, data = BigDays.sfdfT)
summary(modelInitial)

modelInitialPoisson <- glm(nT ~ A + Lat + Lon + CAPE + CIN + DLBS + SLBS, family = "poisson", data = BigDays.sfdfT)
summary(modelInitialPoisson)

modelFinal <- glm.nb(nT ~ A + CAPE + DLBS + SLBS, data = BigDays.sfdfT)
summary(modelFinal)

(exp(coef(modelFinal)) - 1) * 100

hist(resid(modelFinal))
range(exp(predict(modelFinal)))
plot(log(BigDays.sfdfT$nT), predict(modelFinal))
cor(BigDays.sfdfT$nT, predict(modelFinal, type = "response"))
mean(abs(BigDays.sfdfT$nT - predict(modelFinal, type = "response")))
mean(abs(BigDays.sfdfT$nT - predict(modelFinal, type = "response")))/(max(BigDays.sfdfT$nT) - min(BigDays.sfdfT$nT))
mean(abs(BigDays.sfdfT$nT - predict(modelFinal, type = "response")))/(max(predict(modelFinal, type = "response")) - min(predict(modelFinal, type = "response")))


modelglmer.nb <- glmer.nb(nT ~ scale(HullArea) + scale(maxCAPE) + scale(maxBS_deep) + scale(maxBS_shallow) + (1|Season), data = BigDays.sfdfT)
summary(modelglmer.nb) # no convergence if interaction term is included

summary(glm.nb(nT ~ scale(HullArea) + scale(maxCAPE) + scale(avgCIN) + scale(maxBS_deep) + scale(maxBS_shallow), data = BigDays.sfdfT))

modelFinal <- glm.nb(nT ~ HullArea + maxCAPE + maxBS_deep + maxBS_shallow, data = BigDays.sfdfT[BigDays.sfdfT$Mo %in% c(10, 11),])
summary(modelFinal)
```

## Casualty model
```{r}
modelInitialC <- glm.nb(GroupDayCas ~ P + Lat + Lon + Year + CAPE + CIN + DLBS + SLBS, data = BigDays.sfdfT)
summary(modelInitialC)

modelFinalC <- glm.nb(GroupDayCas ~ P + Lat + Lon + Year + CAPE + DLBS + SLBS, data = BigDays.sfdfT)
summary(modelFinalC)

hist(resid(modelFinalC))
range(exp(predict(modelFinalC)))
plot(log(BigDays.sfdfT$GroupDayCas), predict(modelFinalC))
cor(BigDays.sfdfT$GroupDayCas, exp(predict(modelFinalC)))
```

## Cross validation
```{r}
Count <- numeric()
for(i in 1:nrow(BigDays.sfdfT)){
Count[i] <- predict(glm.nb(nT ~ A + CAPE + DLBS + SLBS, data = BigDays.sfdfT[-i, ]), 
                       newdata = BigDays.sfdfT[i,],
                       type = "response")
}
cor(BigDays.sfdfT$nT, Count)
mean(abs(BigDays.sfdfT$nT - Count))
mean(abs(BigDays.sfdfT$nT - Count))/(max(BigDays.sfdfT$nT) - min(BigDays.sfdfT$nT))
mean(abs(BigDays.sfdfT$nT - predict(modelFinal, type = "response")))/(max(predict(modelFinal, type = "response")) - min(predict(modelFinal, type = "response")))

```

## Tornado predictions 1-D
```{r}
theta <- 6.246
nTthresh <- 20
predict(modelFinal, newdata = data.frame(A = c(mean(BigDays.sfdfT$A), mean(BigDays.sfdfT$A)),
                                         CAPE = c(0, 5),
                                         DLBS = c(mean(BigDays.sfdfT$DLBS), mean(BigDays.sfdfT$DLBS)),
                                         SLBS = c(mean(BigDays.sfdfT$SLBS), mean(BigDays.sfdfT$SLBS))),
        type = "response")

1 - pnbinom(nTthresh, size = theta, mu = 18.725) # chance that the outbreak will have more than 50 tornadoes when CAPE = 0
1 - pnbinom(nTthresh, size = theta, mu = 23.55)  # chance that the outbreak will have more than 50 tornadoes when CAPE = 5000

predictions  <- predict(modelFinal, 
                        newdata = data.frame(A = rep(mean(BigDays.sfdfT$A), times = 6),
                                             CAPE = 0:5,
                                             DLBS = rep(mean(BigDays.sfdfT$DLBS), times = 6),
                                             SLBS = rep(mean(BigDays.sfdfT$SLBS), times = 6)),
                        type = "response")
```

```{r}
( CAPElevels <- round(quantile(BigDays.sfdfT$maxCAPE, probs = c(.05, .5, .95))) )
theta <- 6.246
nTthresh <- 30
Area <- 40 # Area of 10\% tor probability April 12, 2020 outbreak 12UTC

predictions  <- predict(modelFinal, 
                        newdata = data.frame(A = Area,
                                             CAPE = CAPElevels[1]/1000,
                                             DLBS = seq(1, 4, by = .25),
                                             SLBS = mean(BigDays.sfdfT$SLBS)),
                        type = "response",
                        se.fit = TRUE)
plot.predictions <- data.frame(CAPE = CAPElevels[1],
                               probability = 1 - pnbinom(nTthresh, size = theta, mu = predictions$fit),
                               probabilityU = 1 - pnbinom(nTthresh, size = theta, mu = predictions$fit + 2 * predictions$se.fit),
                               probabilityL = 1 - pnbinom(nTthresh, size = theta, mu = predictions$fit - 2 * predictions$se.fit),
                               DLBS = seq(1, 4, by = .25) * 10)

predictions  <- predict(modelFinal, 
                        newdata = data.frame(A = Area,
                                             CAPE = CAPElevels[2]/1000,
                                             DLBS = seq(1, 4, by = .25),
                                             SLBS = mean(BigDays.sfdfT$SLBS)),
                        type = "response",
                        se.fit = TRUE)

plot.predictions2 <- data.frame(CAPE = CAPElevels[2],
                               probability = 1 - pnbinom(nTthresh, size = theta, mu = predictions$fit),
                               probabilityU = 1 - pnbinom(nTthresh, size = theta, mu = predictions$fit + 2 * predictions$se.fit),
                               probabilityL = 1 - pnbinom(nTthresh, size = theta, mu = predictions$fit - 2 * predictions$se.fit),
                               DLBS = seq(1, 4, by = .25) * 10)

predictions  <- predict(modelFinal, 
                        newdata = data.frame(A = Area,
                                             CAPE = CAPElevels[3]/1000,
                                             DLBS = seq(1, 4, by = .25),
                                             SLBS = mean(BigDays.sfdfT$SLBS)),
                        type = "response",
                        se.fit = TRUE)

plot.predictions3 <- data.frame(CAPE = CAPElevels[3],
                               probability = 1 - pnbinom(nTthresh, size = theta, mu = predictions$fit),
                               probabilityU = 1 - pnbinom(nTthresh, size = theta, mu = predictions$fit + 2 * predictions$se.fit),
                               probabilityL = 1 - pnbinom(nTthresh, size = theta, mu = predictions$fit - 2 * predictions$se.fit),
                               DLBS = seq(1, 4, by = .25) * 10)


plot.predictions <- rbind(plot.predictions, plot.predictions2, plot.predictions3)


library(ggplot2)
ggplot(plot.predictions, aes(x = DLBS, y = probability, color = factor(CAPE, levels = rev(CAPElevels)))) +
  geom_line(size = 2) +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent) +
  scale_colour_ordinal(name = "CAPE (J/kg)", direction = -1, alpha = .6) +
  ylab(paste("Probability of at least", nTthresh, "tornadoes")) +
  xlab("Deep-layer bulk shear (m/s)") +
  theme_minimal()
```

## Tornado predictions 2-D
```{r}
library(directlabels)

pgrid <- expand.grid(CAPE = seq(1, 5, .05),
                     DLBS = seq(1, 4, .05),
                     A = Area,
                     SLBS = mean(BigDays.sfdfT$SLBS))

predictions <- predict.glm(modelFinal, newdata = pgrid, type = "response")
pgrid$probability <-1 - pnbinom(nTthresh, size = theta, mu = predictions)

( p <- ggplot(pgrid, aes(x = CAPE * 1000, y = DLBS * 10, fill = probability)) +
          geom_raster() +
          scale_fill_viridis_c(alpha = .6) +
#          scale_fill_continuous(low = 'green', high = 'red') +  # use for casualties
          geom_contour(aes(color = ..level.., z = probability), breaks = seq(.3, .6, by = .1), color = "black") +
          ylab("Deep-layer bulk shear (m/s)") +
          xlab("CAPE (J/kg)") + 
          theme_minimal() )
#    ggtitle("Probability of at least 30 tornadoes in an outbreak")
direct.label(p, list("angled.boxes"))
```

## Casualty predictions 1-D
```{r}
( Plevels <- round(quantile(BigDays.sfdfT$P, probs = c(.05, .75, .9)), 2) )
( Plevels <- c(10, 40, 80) )
theta <- .261
nCthresh <- 50
Area <- 40 # Area of 10\% tor probability April 12, 2020 outbreak 12UTC

predictions  <- predict(modelFinalC, 
                        newdata = data.frame(P = Plevels[1],
                                             Lat = mean(BigDays.sfdfT$Lat),
                                             Lon = mean(BigDays.sfdfT$Lon),
                                             Year = 2018,
                                             CAPE = mean(BigDays.sfdfT$CAPE),
                                             DLBS = seq(1, 4, by = .25),
                                             SLBS = mean(BigDays.sfdfT$SLBS)),
                        type = "response",
                        se.fit = TRUE)
plot.predictions <- data.frame(P = Plevels[1],
                               probability = 1 - pnbinom(nCthresh, size = theta, mu = predictions$fit),
                               probabilityU = 1 - pnbinom(nCthresh, size = theta, mu = predictions$fit + 2 * predictions$se.fit),
                               probabilityL = 1 - pnbinom(nCthresh, size = theta, mu = predictions$fit - 2 * predictions$se.fit),
                               DLBS = seq(1, 4, by = .25) * 10)

predictions  <- predict(modelFinalC, 
                        newdata = data.frame(P = Plevels[2],
                                             Lat = mean(BigDays.sfdfT$Lat),
                                             Lon = mean(BigDays.sfdfT$Lon),
                                             Year = 2018,
                                             CAPE = mean(BigDays.sfdfT$CAPE),
                                             DLBS = seq(1, 4, by = .25),
                                             SLBS = mean(BigDays.sfdfT$SLBS)),
                        type = "response",
                        se.fit = TRUE)

plot.predictions2 <- data.frame(P = Plevels[2],
                               probability = 1 - pnbinom(nCthresh, size = theta, mu = predictions$fit),
                               probabilityU = 1 - pnbinom(nCthresh, size = theta, mu = predictions$fit + 2 * predictions$se.fit),
                               probabilityL = 1 - pnbinom(nCthresh, size = theta, mu = predictions$fit - 2 * predictions$se.fit),
                               DLBS = seq(1, 4, by = .25) * 10)

predictions  <- predict(modelFinalC, 
                        newdata = data.frame(P = Plevels[3],
                                             Lat = mean(BigDays.sfdfT$Lat),
                                             Lon = mean(BigDays.sfdfT$Lon),
                                             Year = 2018,
                                             CAPE = mean(BigDays.sfdfT$CAPE),
                                             DLBS = seq(1, 4, by = .25),
                                             SLBS = mean(BigDays.sfdfT$SLBS)),
                        type = "response",
                        se.fit = TRUE)

plot.predictions3 <- data.frame(P = Plevels[3],
                               probability = 1 - pnbinom(nCthresh, size = theta, mu = predictions$fit),
                               probabilityU = 1 - pnbinom(nCthresh, size = theta, mu = predictions$fit + 2 * predictions$se.fit),
                               probabilityL = 1 - pnbinom(nCthresh, size = theta, mu = predictions$fit - 2 * predictions$se.fit),
                               DLBS = seq(1, 4, by = .25) * 10)


plot.predictions <- rbind(plot.predictions, plot.predictions2, plot.predictions3)

library(ggplot2)
ggplot(plot.predictions, aes(x = DLBS, y = probability, color = factor(P * 100000, levels = rev(Plevels * 100000)))) +
  geom_line(size = 2) +
  scale_y_continuous(limits = c(0, .3), labels = scales::percent) +
  scale_colour_ordinal(name = "Population", direction = -1, alpha = .6, labels = c("8,000,000", "4,000,000", "1,000,000")) +
  ylab(paste("Probability of at least", nCthresh, "casualties")) +
  xlab("Deep-layer bulk shear (m/s)") +
  theme_minimal()
```

## April 12, 2020 case https://www.spc.noaa.gov/cgi-bin-spc/getacrange.pl?date0=20200412&date1=20200412
```{r}
library(sf)

read_sf(dsn = "day1otlk_20200412_1200-shp",
                         layer = "day1otlk_20200412_1200_torn") %>%
  st_transform(crs = 3857) %>%
  st_area()

quantile(BigDays.sfdfT$HullArea)
```

## Trends
```{r}
BigDays.sfdfT %>%
#  filter(Mo %in% c(3, 4, 5, 6)) %>%
  group_by(Year) %>%
  summarize(Avg = mean(SLBS)) %>%
ggplot(aes(x = Year, y = Avg)) +
  geom_point() +
  geom_smooth(method = lm)
```

